import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
   role = "teacher"
}: Readonly<{
  children: React.ReactNode;
  role:string
}>) {
   const pathname = usePathname();
  const [shouldRenderSidebar, setShouldRenderSidebar] = useState(false);

  useEffect(() => {

    const excludeSidebarPages = ["/homepage", "/login", "/signup"];
    const currentPathname = pathname;
    const shouldRender = !excludeSidebarPages.includes(currentPathname);
    setShouldRenderSidebar(shouldRender);
  }, [pathname]);

  return (
    <html lang="en">
      <body className={inter.className}>
         {shouldRenderSidebar && <Sidebar role={role} />}
        {children}</body>
    </html>
  );
}